#开发环境的配置
spring:
    application:
        name: dev
    #mongodb
    data:
      mongodb:
        host: 139.224.42.42
        port: 27017
        database: znxz

#日志配置
logging:
  file: F:/springboot.log
  level:
     com.ziniu.webapp : debug
     com.ziniu.control : debug

jasypt:
  encryptor:
    password: ziniu

server:
  port: 8080
  context-path: /
#server.port=8443
# SSL协议相关配置
#server.ssl.key-store= .keystore
#server.ssl.key-password= 123321
#server.ssl.key-store-type= JKS
#server.ssl.key-alias= tomcat

#JWT
jwt:
  header: "Authorization"
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer"
  route:
    authentication:
      path: auth
      refresh: refresh
register: "auth/register"